version: '3.8'
services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pgpassword123
      POSTGRES_DB: opa_db      
    ports:
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistent data storage
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"  
    depends_on:
      - db

  start_infra:
    build: ./src/infra
    container_name: start_infra
    environment:
      DB_CONN: "postgresql://db_user:pgpassword123@db/opa_db"
    depends_on:
      db:
          condition: service_healthy

  spark-master:
    build:
      context: ./src/load_data_etl
      dockerfile: Dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      DOWNLOAD_YEAR: 2024
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./load_data/data:/data

  spark-worker-1:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./load_data/data:/data

  spark-worker-2:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./load_data/data:/data

  # trading_bot_api:
  #   container_name: trading_bot_api
  #   build: ./src
  #   restart: always
  #   ports:
  #     - "8086:8086"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_CONN: "postgresql://db_user:pgpassword123@db/opa_db"

volumes:
  db_data:
    name: db_data
