version: '3.8'
services:
  # binance_connector:
  #   build: .
  #   depends_on:
  #     - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pgpassword123
      POSTGRES_DB: opa_db
    ports:
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistent data storage

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  spark-master:
    build:
      context: ./load_data
      dockerfile: Dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./load_data/data:/data

  spark-worker-1:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./load_data/data:/data

  spark-worker-2:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./load_data/data:/data


volumes:
  db_data:
    name: db_data
